#!/bin/busybox sh

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo 0 > /proc/sys/kernel/printk

cryptsetup luksOpen /dev/sda2 gentoo
mount /dev/mapper/gentoo /mnt

umount /proc
umount /sys
umount /dev

exec switch_root /mnt /sbin/init
